# Coffee Bean Sales

import needed libs

In [19]:
import pandas as pd

In [3]:
tables = pd.read_excel('Raw Data.xlsx', sheet_name=None)

#### Extract the tables from the excel sheet

In [4]:
for table in tables:
    print(table)

orders = tables['orders']
customers = tables['customers']

orders
customers
products

#### Exploring the data

In [5]:
orders.head(5)

,Order ID,Order Date,Customer ID,Product ID,Quantity,Customer Name,Email,Country,Coffee Type,Roast Type,Size,Unit Price,Sales
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
customers.head(5)

,Customer ID,Customer Name,Email,Phone Number,Address Line 1,City,Country,Postcode,Loyalty Card
0,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes
1,73342-18763-UW,Piotr Bote,pbote1@yelp.com,+353 (913) 396-4653,2112 Ridgeway Hill,Crumlin,Ireland,D6W,No
2,21125-22134-PX,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,United States,78205,Yes
3,71253-00052-RN,Dene Azema,dazema3@facebook.com,+1 (217) 418-0714,27 Maywood Place,Springfield,United States,62711,Yes
4,23806-46781-OU,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,Ireland,N41,No

In [7]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer ID     1000 non-null   str
 1   Customer Name   1000 non-null   str
 2   Email           796 non-null    str
 3   Phone Number    870 non-null    str
 4   Address Line 1  1000 non-null   str
 5   City            1000 non-null   str
 6   Country         1000 non-null   str
 7   Postcode        1000 non-null   object
 8   Loyalty Card    1000 non-null   str
dtypes: object(1), str(8)
memory usage: 70.4+ KB

In [8]:
for column in customers.columns:
    print(f"the number of unique in '{column}': {customers[column].nunique()}")

the number of unique in 'Customer ID': 1000
the number of unique in 'Customer Name': 1000
the number of unique in 'Email': 796
the number of unique in 'Phone Number': 870
the number of unique in 'Address Line 1': 1000
the number of unique in 'City': 386
the number of unique in 'Country': 3
the number of unique in 'Postcode': 629
the number of unique in 'Loyalty Card': 2

In [9]:
customers['Country'] = customers['Country'].astype("category")
customers['Loyalty Card'] = customers['Loyalty Card'].astype("category")

In [10]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer ID     1000 non-null   str
 1   Customer Name   1000 non-null   str
 2   Email           796 non-null    str
 3   Phone Number    870 non-null    str
 4   Address Line 1  1000 non-null   str
 5   City            1000 non-null   str
 6   Country         1000 non-null   category
 7   Postcode        1000 non-null   object
 8   Loyalty Card    1000 non-null   category
dtypes: category(2), object(1), str(6)
memory usage: 56.8+ KB

#### check for email validation

In [11]:
email_regex = r'^[^\s@]+@[^\s@]+\.[^\s@]+$'

customers[customers['Email'].str.contains(email_regex, regex=True)]

,Customer ID,Customer Name,Email,Phone Number,Address Line 1,City,Country,Postcode,Loyalty Card
0,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes
1,73342-18763-UW,Piotr Bote,pbote1@yelp.com,+353 (913) 396-4653,2112 Ridgeway Hill,Crumlin,Ireland,D6W,No
2,21125-22134-PX,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,United States,78205,Yes
3,71253-00052-RN,Dene Azema,dazema3@facebook.com,+1 (217) 418-0714,27 Maywood Place,Springfield,United States,62711,Yes
6,65223-29612-CB,Shaylynn Lobe,slobe6@nifty.com,+1 (937) 954-4541,7005 Mariners Cove Place,Dayton,United States,45440,Yes
...,...,...,...,...,...,...,...,...,...
986,51277-93873-RP,Claudell Ayre,cayrere@symantec.com,+1 (386) 573-2575,5645 Lotheville Crossing,Daytona Beach,United States,32128,No
987,84405-83364-DG,Lorianne Kyneton,lkynetonrf@macromedia.com,+44 (618) 634-9365,1926 3rd Center,Seaton,United Kingdom,LE15,Yes
990,98051-37183-SK,Dierdre Scrigmour,dscrigmourri@cnbc.com,+1 (858) 976-1767,018 Luster Pass,Oceanside,United States,92056,No
995,43014-53743-XK,Jennica Tewelson,jtewelsonrn@samsung.com,+1 (469) 573-8379,4040 Hoard Junction,Dallas,United States,75210,No
998,64965-78386-MY,Nicolina Jenny,njennyrq@bigcartel.com,+1 (562) 679-4750,6099 American Ash Court,Whittier,United States,90610,No

In [12]:
customers['Phone Number'].str.len().unique()

array([17., 19., nan, 18.])

In [13]:
customers.head()

,Customer ID,Customer Name,Email,Phone Number,Address Line 1,City,Country,Postcode,Loyalty Card
0,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes
1,73342-18763-UW,Piotr Bote,pbote1@yelp.com,+353 (913) 396-4653,2112 Ridgeway Hill,Crumlin,Ireland,D6W,No
2,21125-22134-PX,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,United States,78205,Yes
3,71253-00052-RN,Dene Azema,dazema3@facebook.com,+1 (217) 418-0714,27 Maywood Place,Springfield,United States,62711,Yes
4,23806-46781-OU,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,Ireland,N41,No

#### Standardize customers columns names for better integration

In [14]:
customers.columns

Index(['Customer ID', 'Customer Name', 'Email', 'Phone Number',
       'Address Line 1', 'City', 'Country', 'Postcode', 'Loyalty Card'],
      dtype='str')

In [15]:
customers.columns = customers.columns.str.lower().str.replace(' ', '_')
customers.columns

Index(['customer_id', 'customer_name', 'email', 'phone_number',
       'address_line_1', 'city', 'country', 'postcode', 'loyalty_card'],
      dtype='str')

#### even with the small amount of null values We will keep it because it's all in the contact info which is not going to effect analysis

In [16]:
print(f" null values: {customers.isna().sum().sum() / (customers.shape[0] * customers.shape[1])*100}%")

 null values: 3.711111111111111%

#### Standardize orders columns names for better integration

In [17]:
print(f"columns names of orders after: {orders.columns}")
orders.columns = orders.columns.str.lower().str.replace(' ', '_')
print(f"columns names of orders before: {orders.columns}")

columns names of orders after: Index(['Order ID', 'Order Date', 'Customer ID', 'Product ID', 'Quantity',
       'Customer Name', 'Email', 'Country', 'Coffee Type', 'Roast Type',
       'Size', 'Unit Price', 'Sales'],
      dtype='str')
columns names of orders before: Index(['order_id', 'order_date', 'customer_id', 'product_id', 'quantity',
       'customer_name', 'email', 'country', 'coffee_type', 'roast_type',
       'size', 'unit_price', 'sales'],
      dtype='str')

In [18]:
customers.to_csv("cleaned data\customers_001.csv", index=False)

<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
C:\Users\Mohamed Abd-Elnour\AppData\Local\Temp\ipykernel_19796\3973778691.py:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  customers.to_csv("cleaned data\customers_001.csv", index=False)