In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [26]:
customers = pd.read_pickle("cleaned data\customers_001.pkl")
products = pd.read_pickle("cleaned data\products_001.pkl")
orders = pd.read_pickle("cleaned data\orders_001.pkl")

<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:3: SyntaxWarning: "\o" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\o"? A raw string is also an option.
<>:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
<>:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:3: SyntaxWarning: "\o" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\o"? A raw string is also an option.
C:\Users\Mohamed Abd-Elnour\AppData\Local\Temp\ipykernel_16296\1589058996.py:1: SyntaxWarning: "\c" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\c"? A raw string is also an option.
  customers = pd.read_pickle("cleaned data\customers_001.pkl")
C:\Users\Mohamed Abd-Elnour\AppData\Local\Temp\ipykernel_16296\1589058996.py:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
  products = pd.read_pickle("cleaned data\products_001.pkl")
C:\Users\Mohamed Abd-Elnour\AppData\Local\Temp\ipykernel_16296\1589058996.py:3: SyntaxWarning: "\o" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\o"? A raw string is also an option.
  orders = pd.read_pickle("cleaned data\orders_001.pkl")

In [27]:
customers.head(5)

,customer_id,customer_name,email,phone_number,address_line_1,city,country,postcode,loyalty_card
0,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes
1,73342-18763-UW,Piotr Bote,pbote1@yelp.com,+353 (913) 396-4653,2112 Ridgeway Hill,Crumlin,Ireland,D6W,No
2,21125-22134-PX,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,United States,78205,Yes
3,71253-00052-RN,Dene Azema,dazema3@facebook.com,+1 (217) 418-0714,27 Maywood Place,Springfield,United States,62711,Yes
4,23806-46781-OU,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,Ireland,N41,No

In [28]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     1000 non-null   str
 1   customer_name   1000 non-null   str
 2   email           796 non-null    str
 3   phone_number    870 non-null    str
 4   address_line_1  1000 non-null   str
 5   city            1000 non-null   str
 6   country         1000 non-null   category
 7   postcode        1000 non-null   object
 8   loyalty_card    1000 non-null   category
dtypes: category(2), object(1), str(6)
memory usage: 56.8+ KB

In [29]:
orders.head()

,order_id,order_date,customer_id,product_id,quantity,customer_name,email,country,coffee_type,roast_type,size,unit_price,sales
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
orders.drop(columns=['customer_name', 'email', 'country', 'coffee_type', 'roast_type', 'size', 'unit_price', 'sales'], inplace=True)

In [31]:
products.head(5)

  product_id coffee_type roast_type  size  unit_price  price_per_100g  profit
0    A-L-0.2         Ara          L   0.2       3.885           1.942   0.350
1    A-L-0.5         Ara          L   0.5       7.770           1.554   0.699
2      A-L-1         Ara          L   1.0      12.950           1.295   1.166
3    A-L-2.5         Ara          L   2.5      29.785           1.191   2.681
4    A-M-0.2         Ara          M   0.2       3.375           1.688   0.304

In [32]:
orders = pd.merge(orders, customers[['customer_id', 'customer_name', 'city', 'country', 'loyalty_card']], on='customer_id', how='left')
orders = pd.merge(orders, products[['product_id', 'coffee_type', 'roast_type', 'size', 'unit_price', 'price_per_100g', 'profit']], on='product_id', how='left')

In [33]:
orders

,order_id,order_date,customer_id,product_id,quantity,customer_name,city,country,loyalty_card,coffee_type,roast_type,size,unit_price,price_per_100g,profit
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,Paterson,United States,Yes,Rob,M,1.0,9.950,0.995,0.597
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,Paterson,United States,Yes,Exc,M,0.5,8.250,1.650,0.908
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,San Antonio,United States,Yes,Ara,L,1.0,12.950,1.295,1.166
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,Cill Airne,Ireland,No,Exc,M,1.0,13.750,1.375,1.512
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,Cill Airne,Ireland,No,Rob,L,2.5,27.485,1.099,1.649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,RLM-96511-467,2020-01-06,43014-53743-XK,R-L-2.5,1,Jennica Tewelson,Dallas,United States,No,Rob,L,2.5,27.485,1.099,1.649
996,AEZ-13242-456,2022-05-04,62494-09113-RP,R-M-0.5,5,Marguerite Graves,Fort Smith,United States,No,Rob,M,0.5,5.970,1.194,0.358
997,UME-75640-698,2019-10-11,62494-09113-RP,A-M-0.5,4,Marguerite Graves,Fort Smith,United States,No,Ara,M,0.5,6.750,1.350,0.607
998,GJC-66474-557,2021-08-03,64965-78386-MY,A-D-1,1,Nicolina Jenny,Whittier,United States,No,Ara,D,1.0,9.950,0.995,0.895
999,IRV-20769-219,2020-10-15,77131-58092-GE,E-M-0.2,3,Vidovic Antonelli,London,United Kingdom,Yes,Exc,M,0.2,4.125,2.062,0.454

In [34]:
orders['sales'] = orders['quantity'] * orders['unit_price']
orders['net_profit'] = orders['quantity'] * orders['profit']

In [35]:
orders

,order_id,order_date,customer_id,product_id,quantity,customer_name,city,country,loyalty_card,coffee_type,roast_type,size,unit_price,price_per_100g,profit,sales,net_profit
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,Paterson,United States,Yes,Rob,M,1.0,9.950,0.995,0.597,19.900,1.194
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,Paterson,United States,Yes,Exc,M,0.5,8.250,1.650,0.908,41.250,4.540
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,San Antonio,United States,Yes,Ara,L,1.0,12.950,1.295,1.166,12.950,1.166
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,Cill Airne,Ireland,No,Exc,M,1.0,13.750,1.375,1.512,27.500,3.024
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,Cill Airne,Ireland,No,Rob,L,2.5,27.485,1.099,1.649,54.970,3.298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,RLM-96511-467,2020-01-06,43014-53743-XK,R-L-2.5,1,Jennica Tewelson,Dallas,United States,No,Rob,L,2.5,27.485,1.099,1.649,27.485,1.649
996,AEZ-13242-456,2022-05-04,62494-09113-RP,R-M-0.5,5,Marguerite Graves,Fort Smith,United States,No,Rob,M,0.5,5.970,1.194,0.358,29.850,1.790
997,UME-75640-698,2019-10-11,62494-09113-RP,A-M-0.5,4,Marguerite Graves,Fort Smith,United States,No,Ara,M,0.5,6.750,1.350,0.607,27.000,2.428
998,GJC-66474-557,2021-08-03,64965-78386-MY,A-D-1,1,Nicolina Jenny,Whittier,United States,No,Ara,D,1.0,9.950,0.995,0.895,9.950,0.895
999,IRV-20769-219,2020-10-15,77131-58092-GE,E-M-0.2,3,Vidovic Antonelli,London,United Kingdom,Yes,Exc,M,0.2,4.125,2.062,0.454,12.375,1.362