In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [54]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\Users\MOAYAD\AppData\Local\Programs\Python\Python313\Lib\site-packages (24.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [55]:
products=pd.read_pickle("cleaned data/products_001.pkl")
orders=pd.read_pickle("cleaned data/orders_001.pkl")
customers=pd.read_pickle("cleaned data/customers_001.pkl")

In [81]:
customers.head(5)

,customer_id,customer_name,email,phone_number,address_line_1,city,country,postcode,loyalty_card
0,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,+1 (862) 817-0124,57999 Pepper Wood Alley,Paterson,United States,7505,Yes
1,73342-18763-UW,Piotr Bote,pbote1@yelp.com,+353 (913) 396-4653,2112 Ridgeway Hill,Crumlin,Ireland,D6W,No
2,21125-22134-PX,Jami Redholes,jredholes2@tmall.com,+1 (210) 986-6806,5214 Bartillon Park,San Antonio,United States,78205,Yes
3,71253-00052-RN,Dene Azema,dazema3@facebook.com,+1 (217) 418-0714,27 Maywood Place,Springfield,United States,62711,Yes
4,23806-46781-OU,Christoffer O' Shea,NaN,+353 (698) 362-9201,38980 Manitowish Junction,Cill Airne,Ireland,N41,No

In [57]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     1000 non-null   str
 1   customer_name   1000 non-null   str
 2   email           796 non-null    str
 3   phone_number    870 non-null    str
 4   address_line_1  1000 non-null   str
 5   city            1000 non-null   str
 6   country         1000 non-null   category
 7   postcode        1000 non-null   object
 8   loyalty_card    1000 non-null   category
dtypes: category(2), object(1), str(6)
memory usage: 56.8+ KB

In [58]:
products.head(5)
orders.head(5)

,order_id,order_date,customer_id,product_id,quantity,customer_name,email,country,coffee_type,roast_type,size,unit_price,sales
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# This prevents the 'ValueError: columns overlap' we saw earlier
cols_to_fix = ['customer_name', 'email', 'country']
orders = orders.drop(columns=cols_to_fix, errors='ignore')

# 3. Perform the Left Merge
# This matches every order to its customer details in one shot
orders = pd.merge(orders, customers[['customer_id', 'customer_name', 'email', 'country']], 
                  on='customer_id', 
                  how='left')

In [71]:
orders.head(5)

,order_id,order_date,customer_id,product_id,quantity,customer_name,email,country,coffee_type,roast_type,size,unit_price,profit
0,QEV-37451-860,2019-09-05,17670-51384-MA,R-M-1,2,Aloisia Allner,aallner0@lulu.com,United States,Rob,M,1.0,9.950,0.597
1,QEV-37451-860,2019-09-05,17670-51384-MA,E-M-0.5,5,Aloisia Allner,aallner0@lulu.com,United States,Exc,M,0.5,8.250,0.908
2,FAA-43335-268,2021-06-17,21125-22134-PX,A-L-1,1,Jami Redholes,jredholes2@tmall.com,United States,Ara,L,1.0,12.950,1.166
3,KAC-83089-793,2021-07-15,23806-46781-OU,E-M-1,2,Christoffer O' Shea,NaN,Ireland,Exc,M,1.0,13.750,1.512
4,KAC-83089-793,2021-07-15,23806-46781-OU,R-L-2.5,2,Christoffer O' Shea,NaN,Ireland,Rob,L,2.5,27.485,1.649

In [68]:
products.head(5)

  product_id coffee_type roast_type  size  unit_price  price_per_100g  profit
0    A-L-0.2         Ara          L   0.2       3.885           1.942   0.350
1    A-L-0.5         Ara          L   0.5       7.770           1.554   0.699
2      A-L-1         Ara          L   1.0      12.950           1.295   1.166
3    A-L-2.5         Ara          L   2.5      29.785           1.191   2.681
4    A-M-0.2         Ara          M   0.2       3.375           1.688   0.304

In [72]:
# 3. Perform the Left Merge
# This matches every order to its product details in one shot
orders = pd.merge(orders, products[['product_id', 'coffee_type', 'roast_type', 'size', 'unit_price','profit']], 
                  on='product_id', 
                  how='left')

In [93]:
orders.head(5)

,order_id,order_date,customer_id,customer_name,email,city,country,loyalty_card,product_id,coffee_type,roast_type,size,quantity,unit_price,sales,profit_per_item,net_profit
0,QEV-37451-860,2019-09-05,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,Paterson,United States,Yes,R-M-1,Rob,M,1.0,2,9.950,19.90,0.597,1.194
1,QEV-37451-860,2019-09-05,17670-51384-MA,Aloisia Allner,aallner0@lulu.com,Paterson,United States,Yes,E-M-0.5,Exc,M,0.5,5,8.250,41.25,0.908,4.540
2,FAA-43335-268,2021-06-17,21125-22134-PX,Jami Redholes,jredholes2@tmall.com,San Antonio,United States,Yes,A-L-1,Ara,L,1.0,1,12.950,12.95,1.166,1.166
3,KAC-83089-793,2021-07-15,23806-46781-OU,Christoffer O' Shea,NaN,Cill Airne,Ireland,No,E-M-1,Exc,M,1.0,2,13.750,27.50,1.512,3.024
4,KAC-83089-793,2021-07-15,23806-46781-OU,Christoffer O' Shea,NaN,Cill Airne,Ireland,No,R-L-2.5,Rob,L,2.5,2,27.485,54.97,1.649,3.298

In [75]:
# Delete columns ending with "_y" and rename columns ending with "_x" (remove "_x")
orders = orders.loc[:, ~orders.columns.str.endswith('_y')]
orders.columns = orders.columns.str.replace('_x', '', regex=False)

In [83]:
# Merge loyalty from customers with orders
orders = pd.merge(orders, customers[['customer_id', 'loyalty_card']], 
                  on='customer_id', 
                  how='left')

In [85]:
# Clean up duplicate loyalty columns
orders = orders.drop(columns=['loyalty_card_y'], errors='ignore')
orders = orders.rename(columns={'loyalty_card_x': 'loyalty_card'})

In [88]:
# Merge city from customers with orders
orders = pd.merge(orders, customers[['customer_id', 'city']], 
                  on='customer_id', 
                  how='left')

In [92]:
# Sort columns with logical order: Order Info → Customer Info → Product Info → Transaction Details
column_order = [
    'order_id', 'order_date',                    # Order identifiers
    'customer_id', 'customer_name', 'email', 'city', 'country', 'loyalty_card',  # Customer info
    'product_id', 'coffee_type', 'roast_type', 'size',  # Product info
    'quantity', 'unit_price', 'sales', 'profit_per_item', 'net_profit'  # Transaction details
]
orders = orders[column_order]

In [94]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         1000 non-null   str
 1   order_date       1000 non-null   datetime64[us]
 2   customer_id      1000 non-null   str
 3   customer_name    1000 non-null   str
 4   email            794 non-null    str
 5   city             1000 non-null   str
 6   country          1000 non-null   category
 7   loyalty_card     1000 non-null   category
 8   product_id       1000 non-null   str
 9   coffee_type      1000 non-null   category
 10  roast_type       1000 non-null   category
 11  size             1000 non-null   float64
 12  quantity         1000 non-null   int64
 13  unit_price       1000 non-null   float64
 14  sales            1000 non-null   float64
 15  profit_per_item  1000 non-null   float64
 16  net_profit       1000 non-null   float64
dtypes: category(4), datetime64[us](1), float64(5), int64(1), str(6)
memory usage: 105.8 KB

In [77]:
orders.rename(columns={'profit': 'profit_per_item'}, inplace=True)

In [79]:
orders['sales'] = orders['quantity'] * orders['unit_price']
orders['net_profit'] = orders['quantity'] * orders['profit_per_item']

In [87]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         1000 non-null   str
 1   order_date       1000 non-null   datetime64[us]
 2   customer_id      1000 non-null   str
 3   product_id       1000 non-null   str
 4   quantity         1000 non-null   int64
 5   customer_name    1000 non-null   str
 6   email            794 non-null    str
 7   country          1000 non-null   category
 8   coffee_type      1000 non-null   category
 9   roast_type       1000 non-null   category
 10  size             1000 non-null   float64
 11  unit_price       1000 non-null   float64
 12  profit_per_item  1000 non-null   float64
 13  sales            1000 non-null   float64
 14  net_profit       1000 non-null   float64
 15  loyalty_card     1000 non-null   category
dtypes: category(4), datetime64[us](1), float64(5), int64(1), str(5)
memory usage: 98.0 KB