In [ ]:
import pandas as pd 
import numpy as np 
import seaborn as sns s
import matplotlib as plt
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
customers = pd.read_excel("Raw Data.xlsx", sheet_name="customers")
orders = pd.read_excel("Raw Data.xlsx", sheet_name="orders")
products = pd.read_excel("Raw Data.xlsx", sheet_name="products")

In [ ]:
products.head()

  Product ID Coffee Type Roast Type  Size  Unit Price  Price per 100g   Profit
0    A-L-0.2         Ara          L   0.2       3.885          1.9425  0.34965
1    A-L-0.5         Ara          L   0.5       7.770          1.5540  0.69930
2      A-L-1         Ara          L   1.0      12.950          1.2950  1.16550
3    A-L-2.5         Ara          L   2.5      29.785          1.1914  2.68065
4    A-M-0.2         Ara          M   0.2       3.375          1.6875  0.30375

In [16]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product ID      48 non-null     str
 1   Coffee Type     48 non-null     str
 2   Roast Type      48 non-null     str
 3   Size            48 non-null     float64
 4   Unit Price      48 non-null     float64
 5   Price per 100g  48 non-null     float64
 6   Profit          48 non-null     float64
dtypes: float64(4), str(3)
memory usage: 2.8 KB

In [17]:
products.rename(columns={"Product ID":"product_id"})

,product_id,Coffee Type,Roast Type,Size,Unit Price,Price per 100g,Profit
0,A-L-0.2,Ara,L,0.2,3.885,1.9425,0.34965
1,A-L-0.5,Ara,L,0.5,7.770,1.5540,0.69930
2,A-L-1,Ara,L,1.0,12.950,1.2950,1.16550
3,A-L-2.5,Ara,L,2.5,29.785,1.1914,2.68065
4,A-M-0.2,Ara,M,0.2,3.375,1.6875,0.30375
5,A-M-0.5,Ara,M,0.5,6.750,1.3500,0.60750
6,A-M-1,Ara,M,1.0,11.250,1.1250,1.01250
7,A-M-2.5,Ara,M,2.5,25.875,1.0350,2.32875
8,A-D-0.2,Ara,D,0.2,2.985,1.4925,0.26865
9,A-D-0.5,Ara,D,0.5,5.970,1.1940,0.53730
10,A-D-1,Ara,D,1.0,9.950,0.9950,0.89550
11,A-D-2.5,Ara,D,2.5,22.885,0.9154,2.05965
12,R-L-0.2,Rob,L,0.2,3.585,1.7925,0.21510
13,R-L-0.5,Rob,L,0.5,7.170,1.4340,0.43020
14,R-L-1,Rob,L,1.0,11.950,1.1950,0.71700
15,R-L-2.5,Rob,L,2.5,27.485,1.0994,1.64910
16,R-M-0.2,Rob,M,0.2,2.985,1.4925,0.17910
17,R-M-0.5,Rob,M,0.5,5.970,1.1940,0.35820
18,R-M-1,Rob,M,1.0,9.950,0.9950,0.59700
19,R-M-2.5,Rob,M,2.5,22.885,0.9154,1.37310
20,R-D-0.2,Rob,D,0.2,2.685,1.3425,0.16110
21,R-D-0.5,Rob,D,0.5,5.370,1.0740,0.32220
22,R-D-1,Rob,D,1.0,8.950,0.8950,0.53700
23,R-D-2.5,Rob,D,2.5,20.585,0.8234,1.23510
24,L-L-0.2,Lib,L,0.2,4.755,2.3775,0.61815
25,L-L-0.5,Lib,L,0.5,9.510,1.9020,1.23630
26,L-L-1,Lib,L,1.0,15.850,1.5850,2.06050
27,L-L-2.5,Lib,L,2.5,36.455,1.4582,4.73915
28,L-M-0.2,Lib,M,0.2,4.365,2.1825,0.56745
29,L-M-0.5,Lib,M,0.5,8.730,1.7460,1.13490
30,L-M-1,Lib,M,1.0,14.550,1.4550,1.89150
31,L-M-2.5,Lib,M,2.5,33.465,1.3386,4.35045
32,L-D-0.2,Lib,D,0.2,3.885,1.9425,0.50505
33,L-D-0.5,Lib,D,0.5,7.770,1.5540,1.01010
34,L-D-1,Lib,D,1.0,12.950,1.2950,1.68350
35,L-D-2.5,Lib,D,2.5,29.785,1.1914,3.87205
36,E-L-0.2,Exc,L,0.2,4.455,2.2275,0.49005
37,E-L-0.5,Exc,L,0.5,8.910,1.7820,0.98010
38,E-L-1,Exc,L,1.0,14.850,1.4850,1.63350
39,E-L-2.5,Exc,L,2.5,34.155,1.3662,3.75705
40,E-M-0.2,Exc,M,0.2,4.125,2.0625,0.45375
41,E-M-0.5,Exc,M,0.5,8.250,1.6500,0.90750
42,E-M-1,Exc,M,1.0,13.750,1.3750,1.51250
43,E-M-2.5,Exc,M,2.5,31.625,1.2650,3.47875
44,E-D-0.2,Exc,D,0.2,3.645,1.8225,0.40095
45,E-D-0.5,Exc,D,0.5,7.290,1.4580,0.80190
46,E-D-1,Exc,D,1.0,12.150,1.2150,1.33650
47,E-D-2.5,Exc,D,2.5,27.945,1.1178,3.07395

In [23]:
products.columns=products.columns.str.lower().str.replace(" ","_")
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      48 non-null     str
 1   coffee_type     48 non-null     str
 2   roast_type      48 non-null     str
 3   size            48 non-null     float64
 4   unit_price      48 non-null     float64
 5   price_per_100g  48 non-null     float64
 6   profit          48 non-null     float64
dtypes: float64(4), str(3)
memory usage: 2.8 KB

In [ ]:
products.info()